name: Handle Form Submission

on:
  repository_dispatch:
    types: [form_submission]

jobs:
  process-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update subscribers CSV
        run: |
          # Create subscribers.csv if it doesn't exist
          if [ ! -f subscribers.csv ]; then
            echo "email,name,company,device,markets,message,date" > subscribers.csv
          fi
          
          # Add new submission to CSV
          echo "${{ github.event.client_payload.email }},${{ github.event.client_payload.name }},${{ github.event.client_payload.company }},${{ github.event.client_payload.device }},${{ github.event.client_payload.markets }},${{ github.event.client_payload.message }},$(date +%Y-%m-%d)" >> subscribers.csv
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add subscribers.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add new subscriber" && git push) 